/*
 * test_wasm.mjs - checks the WebAssembly build gives the same answers as the
 * native one.
 *
 * Run:  node web/test_wasm.mjs
 *
 * It feeds the wasm module an impulse train ringing a resonance, which is what
 * a damaged bearing produces, and requires the envelope analysis to find the
 * impact rate it was given. Same idea as the native envelope tests.
 */

import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const createCSpectrum = require("../docs/spindoctor/cspectrum.js");

const FS = 48000;
const FFT = 2048;
const HOP = 512;

let failures = 0;
function check(cond, msg) {
  if (cond) {
    console.log("  ok    " + msg);
  } else {
    console.log("  FAIL  " + msg);
    failures++;
  }
}

const M = await createCSpectrum();

const api = {
  init: M.cwrap("csw_init", "number", ["number","number","number","number","number"]),
  inPtr: M.cwrap("csw_input_ptr", "number", []),
  push: M.cwrap("csw_push", "number", ["number"]),
  feature: M.cwrap("csw_feature", "number", ["number"]),
  envAnalyse: M.cwrap("csw_analyse_envelope", null, []),
  envReady: M.cwrap("csw_env_ready", "number", []),
  envHz: M.cwrap("csw_env_hz", "number", []),
  envProm: M.cwrap("csw_env_prominence", "number", []),
  monStart: M.cwrap("csw_monitor_start", null, []),
  state: M.cwrap("csw_state", "number", []),
  free: M.cwrap("csw_free", null, []),
};

/* Feeds a signal generated by fn(t) through the module. */
function run(fn, seconds) {
  if (!api.init(FS, FFT, HOP, 2000, 6000)) throw new Error("csw_init failed");
  const ptr = api.inPtr();
  const CH = 4096;
  const total = Math.floor(FS * seconds);

  for (let off = 0; off < total; off += CH) {
    const n = Math.min(CH, total - off);
    const view = M.HEAPF32.subarray(ptr / 4, ptr / 4 + n);
    for (let i = 0; i < n; i++) view[i] = fn((off + i) / FS, off + i);
    api.push(n);
  }
  api.envAnalyse();
}

/* Deterministic noise, matching the C generator's shape. */
let seed = 12345 >>> 0;
function noise() {
  let s = 0;
  for (let k = 0; k < 3; k++) {
    seed ^= seed << 13; seed >>>= 0;
    seed ^= seed >>> 17;
    seed ^= seed << 5;  seed >>>= 0;
    s += seed / 2147483648 - 1;
  }
  return s;
}

console.log("wasm module loaded\n");

/* ---- 1. a pure tone ---- */
console.log("pure 1 kHz tone");
run((t) => 0.5 * Math.sin(2 * Math.PI * 1000 * t), 3);
{
  const crest = api.feature(1);
  const kurt  = api.feature(2);
  check(Math.abs(crest - Math.SQRT2) < 0.05, `crest ${crest.toFixed(3)} is about sqrt(2)`);
  check(Math.abs(kurt - 1.5) < 0.2, `kurtosis ${kurt.toFixed(3)} is about 1.5 for a sine`);
}

/* ---- 2. impacts at a known rate ---- */
console.log("\nimpacts at 107 Hz ringing a 3.8 kHz resonance");
{
  const RATE = 107;
  const RES = 3800;
  const DECAY = 700;      // ring decay, 1/s
  let lastImpact = 0;
  let phase = 0;

  seed = 999 >>> 0;
  run((t) => {
    // start a new ring every 1/RATE seconds
    while (t >= lastImpact + 1 / RATE) { lastImpact += 1 / RATE; phase = 0; }
    const age = t - lastImpact;
    const ring = Math.exp(-age * DECAY) * Math.sin(2 * Math.PI * RES * age);
    return 0.02 * noise() + 0.5 * ring;
  }, 6);

  check(api.envReady() === 1, "envelope has enough data");
  const hz = api.envHz();
  const prom = api.envProm();
  check(Math.abs(hz - RATE) < RATE * 0.06,
        `envelope peak ${hz.toFixed(1)} Hz is the 107 Hz impact rate`);
  check(prom > 8, `prominence ${prom.toFixed(1)} is well above the 8 gate`);
  check(api.feature(2) > 4, `kurtosis ${api.feature(2).toFixed(2)} is high for impacts`);
}

/* ---- 3. plain noise should look like nothing ---- */
console.log("\nbroadband noise");
{
  seed = 4242 >>> 0;
  run(() => 0.1 * noise(), 6);
  const prom = api.envProm();
  check(prom < 8, `prominence ${prom.toFixed(1)} stays under the gate`);
  check(api.feature(2) < 4, `kurtosis ${api.feature(2).toFixed(2)} is low`);
  check(api.feature(4) > 0.3, `flatness ${api.feature(4).toFixed(2)} is high for noise`);
}

/* ---- 4. the baseline monitor runs ---- */
console.log("\nbaseline monitor");
{
  api.init(FS, FFT, HOP, 2000, 6000);
  api.monStart();
  check(api.state() === 0, "starts in the learning state");

  const ptr = api.inPtr();
  seed = 7 >>> 0;
  for (let b = 0; b < 900; b++) {
    const view = M.HEAPF32.subarray(ptr / 4, ptr / 4 + 512);
    for (let i = 0; i < 512; i++) view[i] = 0.1 * noise();
    api.push(512);
  }
  check(api.state() === 1, `settles to OK after learning (state ${api.state()})`);
}

api.free();

console.log(failures ? `\n${failures} checks failed` : "\nall wasm checks passed");
process.exit(failures ? 1 : 0);
